-- for H2DB
CREATE TABLE IF NOT EXISTS person (ID BIGINT auto_increment PRIMARY KEY, NAME VARCHAR(255), COMPANY_ID BIGINT);
CREATE TABLE IF NOT EXISTS company (ID BIGINT auto_increment PRIMARY KEY, NAME VARCHAR(255));


