package me.masahito.dao

import com.googlecode.mapperdao.{ValuesMap, SurrogateIntId, Entity}

class Company(val name: String)

object CompanyEntity extends Entity[Int,SurrogateIntId, Company] {
  val id = key("id") autogenerated (_.id)
  val name = column("name") to (_.name)

  def constructor(implicit m: ValuesMap) = new Company(name) with Stored {
    val id: Int = CompanyEntity.id
  }
}
